# Generated by Django 4.2.16 on 2024-11-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("deactivate", "Can deactivate mailing"),
                    ("view_all", "Can view all mailings"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
